"""Live signal outcome logger — records every signal with its market outcome.

Tracks: signal details, indicator snapshot, regime, bias, session phase,
and whether the trade would have been profitable (price hit target or stop first).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

LOG_DIR = Path(__file__).resolve().parent.parent.parent / "logs" / "ml"
SIGNAL_LOG = LOG_DIR / "live_signals.jsonl"
OUTCOME_LOG = LOG_DIR / "signal_outcomes.jsonl"


class LiveSignalLogger:
    """Logs every live signal and tracks outcomes for ML training.

    Every signal generated by the scanner is logged with:
    - All indicator values at signal time
    - Regime, bias, session phase
    - Direction, entry, stop, target, strength, reasons
    - Later: outcome (win/loss/timeout)
    """

    def __init__(self):
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        self._pending: Dict[str, Dict[str, Any]] = {}  # signals awaiting outcome

    def log_signal(
        self,
        instrument: str,
        signal: Dict[str, Any],
        indicators: Dict[str, Any],
        regime: str,
        bias: str = "neutral",
        session_phase: str = "",
        entry_timeframe: str = "5m",
        trends: Optional[Dict[str, str]] = None,
    ) -> str:
        """Log a new signal. Returns a signal_id for outcome tracking."""
        signal_id = f"{instrument}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"

        record = {
            "signal_id": signal_id,
            "timestamp": datetime.utcnow().isoformat(),
            "instrument": instrument,
            "direction": signal.get("direction"),
            "price": signal.get("price"),
            "stop": signal.get("stop"),
            "target": signal.get("target"),
            "strength": signal.get("strength"),
            "reasons": signal.get("reasons", []),
            "regime": regime,
            "bias": bias,
            "session_phase": session_phase,
            "entry_timeframe": entry_timeframe,
            "trends": trends or {},
            # Indicator snapshot — the ML features
            "indicators": {
                # Classic indicators
                "ema_spread": indicators.get("ema_fast", 0) - indicators.get("ema_slow", 0),
                "rsi": indicators.get("rsi", 0),
                "adx": indicators.get("adx", 0),
                "macd_hist": indicators.get("macd_hist", 0),
                "atr": indicators.get("atr", 0),
                "vwap_distance": indicators.get("close", 0) - indicators.get("vwap", 0),
                "close": indicators.get("close", 0),
                "aggression": indicators.get("aggression", 0),
                # Microstructure — Phase A (position/flow)
                "orb_distance_15": indicators.get("orb_distance_15", 0),
                "orb_range_15": indicators.get("orb_range_15", 0),
                "orb_broke_dir": indicators.get("orb_broke_dir", 0),
                "vwap_sigma_distance": indicators.get("vwap_sigma_distance", 0),
                "cum_delta": indicators.get("cum_delta", 0),
                "delta_change": indicators.get("delta_change", 0),
                # Microstructure — Phase B (liquidity/activity)
                "rv_iv_ratio_5m": indicators.get("rv_iv_ratio_5m", 0),
                "spread_percentile": indicators.get("spread_percentile", 0),
                "spread_z_score": indicators.get("spread_z_score", 0),
                "vol_burst_ratio": indicators.get("vol_burst_ratio", 0),
                # Microstructure — Phase C (inter-market)
                "xcorr_ind": indicators.get("xcorr_ind", 0),
                "xcorr_es": indicators.get("xcorr_es", 0),
                "leadlag_best_corr": indicators.get("leadlag_best_corr", 0),
                "leadlag_best_lag": indicators.get("leadlag_best_lag", 0),
                "risk_regime_score": indicators.get("risk_regime_score", 0),
            },
            # Outcome fields — filled later
            "outcome": None,  # "win", "loss", "timeout", "breakeven"
            "exit_price": None,
            "pnl_pts": None,
            "bars_to_exit": None,
        }

        # Write to log
        with open(SIGNAL_LOG, "a") as f:
            f.write(json.dumps(record, default=str) + "\n")

        # Track for outcome resolution
        self._pending[signal_id] = record

        logger.info("ML LOG: %s %s %s @ %.2f str=%.2f [%s]",
                     instrument, signal.get("direction"), regime,
                     signal.get("price", 0), signal.get("strength", 0),
                     ",".join(signal.get("reasons", [])[:3]))

        return signal_id

    def check_outcomes(self, instrument: str, current_price: float, bars_elapsed: int = 1) -> List[Dict[str, Any]]:
        """Check if any pending signals hit their target or stop.

        Call this every scan cycle with the current price.

        Returns list of resolved signals.
        """
        resolved = []
        to_remove = []

        for sig_id, record in self._pending.items():
            if record["instrument"] != instrument:
                continue

            direction = record["direction"]
            stop = record.get("stop", 0)
            target = record.get("target", 0)
            entry = record.get("price", 0)

            if not stop or not target or not entry:
                continue

            # Increment bars counter
            if "bars_counted" not in record:
                record["bars_counted"] = 0
            record["bars_counted"] += 1

            # Check if target hit
            if direction == "long" and current_price >= target:
                record["outcome"] = "win"
                record["exit_price"] = target
                record["pnl_pts"] = target - entry
                record["bars_to_exit"] = record["bars_counted"]
                resolved.append(record)
                to_remove.append(sig_id)

            elif direction == "short" and current_price <= target:
                record["outcome"] = "win"
                record["exit_price"] = target
                record["pnl_pts"] = entry - target
                record["bars_to_exit"] = record["bars_counted"]
                resolved.append(record)
                to_remove.append(sig_id)

            # Check if stop hit
            elif direction == "long" and current_price <= stop:
                record["outcome"] = "loss"
                record["exit_price"] = stop
                record["pnl_pts"] = stop - entry
                record["bars_to_exit"] = record["bars_counted"]
                resolved.append(record)
                to_remove.append(sig_id)

            elif direction == "short" and current_price >= stop:
                record["outcome"] = "loss"
                record["exit_price"] = stop
                record["pnl_pts"] = entry - stop
                record["bars_to_exit"] = record["bars_counted"]
                resolved.append(record)
                to_remove.append(sig_id)

            # Timeout after 60 bars (~5 hours on 5-min bars)
            elif record["bars_counted"] > 60:
                record["outcome"] = "timeout"
                record["exit_price"] = current_price
                record["pnl_pts"] = (current_price - entry) if direction == "long" else (entry - current_price)
                record["bars_to_exit"] = record["bars_counted"]
                resolved.append(record)
                to_remove.append(sig_id)

        # Write outcomes and remove from pending
        for record in resolved:
            with open(OUTCOME_LOG, "a") as f:
                f.write(json.dumps(record, default=str) + "\n")
            logger.info("ML OUTCOME: %s %s %s pnl=%.2f pts (%d bars)",
                         record["instrument"], record["direction"], record["outcome"],
                         record.get("pnl_pts", 0), record.get("bars_to_exit", 0))

        for sig_id in to_remove:
            del self._pending[sig_id]

        return resolved

    def get_training_data(self) -> list:
        """Load all resolved signals from the outcome log for ML training."""
        if not OUTCOME_LOG.exists():
            return []
        records = []
        with open(OUTCOME_LOG) as f:
            for line in f:
                if line.strip():
                    records.append(json.loads(line))
        return records

    @property
    def pending_count(self) -> int:
        return len(self._pending)

    @property
    def total_logged(self) -> int:
        if not SIGNAL_LOG.exists():
            return 0
        with open(SIGNAL_LOG) as f:
            return sum(1 for _ in f)

    @property
    def total_outcomes(self) -> int:
        if not OUTCOME_LOG.exists():
            return 0
        with open(OUTCOME_LOG) as f:
            return sum(1 for _ in f)

    def stats(self) -> Dict[str, Any]:
        """Return ML logging statistics."""
        outcomes = self.get_training_data()
        wins = sum(1 for o in outcomes if o.get("outcome") == "win")
        losses = sum(1 for o in outcomes if o.get("outcome") == "loss")
        timeouts = sum(1 for o in outcomes if o.get("outcome") == "timeout")
        total = len(outcomes)

        return {
            "total_signals_logged": self.total_logged,
            "total_outcomes": total,
            "pending": self.pending_count,
            "wins": wins,
            "losses": losses,
            "timeouts": timeouts,
            "win_rate": round(wins / max(total - timeouts, 1) * 100, 1),
            "avg_bars_to_exit": round(sum(o.get("bars_to_exit", 0) for o in outcomes) / max(total, 1), 1),
        }
